### ISSUE TITLE
File "/root/ISE_Certificate_Tool/cert_tool.py", line 318, in <module>

### ISSUE THREAD

**Issue by ArxDen** [Anasca2024/ISE_Certification_Tool#2]
python cert_tool.py -l -n 192.168.1.11 -u user -p password
Testing connection to 192.168.1.11...
Connection to 192.168.1.11 Successful!!!
Traceback (most recent call last):
  File "/root/ISE_Certificate_Tool/cert_tool.py", line 318, in <module>
    hostname2 = api.node_details.get_node_details().response.SearchResult.resources[0].name
AttributeError: 'str' object has no attribute 'SearchResult'

**Comment by ArxDen** [comment]
Need to create a special user with rights ERS/OpenAPI admin and use it for request
